name: deploy-api-docs
on:
   push:
     branches:
       - master

jobs:
  deploy:
    name: api.pinhan.codes
    runs-on: ubuntu-latest
    steps:
    - name: Deploy api-docs
      uses: appleboy/ssh-action@master
      with:
        host: pinhan.codes
        username: pinhan
        key: ${{ secrets.pinhan_CODES_SSH_KEY }}
        script: ./github-actions/deploy-api-docs.sh
